
server:
  port: 8090

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Robert-VSol/java-academia-ms-country-services
          clone-on-start: true
#  profiles:
#    active: native